### PR TITLE
fix typo in getting-started.mdx 

### PR DESCRIPTION
**Pull request by Seemeon20**
with an API smiliar to [docker-compose](https://docs.docker.com/compose/). Put similar in place of smiliar

### CODE REVIEW

**Comment by royra** [comment]
Hey @Seemeon20, thanks for your PR! Looks like you were basing it off an old branch (`master` instead of `main`?). Can you rebase and see if it's still relevant?

**Comment by Seemeon20** [comment]
Please why is this closed

**Comment by royra** [comment]
@Seemeon20 see my comment above

**Comment by Seemeon20** [comment]
Okay I don't know how to do that but I'll be okay to further my contributions in other ways

**Pull request closed without merging**
